
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action AboutButton;

	private global::Gtk.Action QuitButton;

	private global::Gtk.Fixed MainLayout;

	private global::Gtk.Notebook MainNotebook;

	private global::Gtk.Fixed LayoutPageData;

	private global::Gtk.Label LabelTrainingData;

	private global::Gtk.Entry FilenameTrainingData;

	private global::Gtk.ScrolledWindow WindowTrainingData;

	private global::Gtk.TextView ViewTrainingData;

	private global::Gtk.Label LabelTestData;

	private global::Gtk.Entry FilenameTestData;

	private global::Gtk.ScrolledWindow WindowTestData;

	private global::Gtk.TextView ViewTestData;

	private global::Gtk.Button OpenTrainingDataButton;

	private global::Gtk.Button ReloadTrainingDataButton;

	private global::Gtk.Button OpenTestDataButton;

	private global::Gtk.Button ReloadTestDataButton;

	private global::Gtk.Label LabelDelimiters;

	private global::Gtk.ComboBox DelimiterBox;

	private global::Gtk.Label LabelInputNodes;

	private global::Gtk.SpinButton InputLayerNodes;

	private global::Gtk.Label LabelCategories;

	private global::Gtk.SpinButton Categories;

	private global::Gtk.Label label11;

	private global::Gtk.SpinButton Examples;

	private global::Gtk.Label LabelSamples;

	private global::Gtk.SpinButton Samples;

	private global::Gtk.Label LabelPageData;

	private global::Gtk.Fixed LayoutPageTraining;

	private global::Gtk.Label LabelPageTraining;

	private global::Gtk.Fixed LayoutPageNetwork;

	private global::Gtk.Label LabelPageNetwork;

	private global::Gtk.Fixed LayoutPagePlot;

	private global::Gtk.Label LabelPagePlot;

	private global::Gtk.Fixed LayoutPageAbout;

	private global::Gtk.Label LabelPageAbout;

	private global::Gtk.Toolbar MainToolbar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.AboutButton = new global::Gtk.Action("AboutButton", null, global::Mono.Unix.Catalog.GetString("About Deep Neural Network Classifier"), "gtk-dialog-info");
		w1.Add(this.AboutButton, null);
		this.QuitButton = new global::Gtk.Action("QuitButton", null, global::Mono.Unix.Catalog.GetString("Exit Deep Neural Network Classifier"), "gtk-quit");
		w1.Add(this.QuitButton, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.WidthRequest = 800;
		this.HeightRequest = 600;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainLayout = new global::Gtk.Fixed();
		this.MainLayout.Name = "MainLayout";
		this.MainLayout.HasWindow = false;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.MainNotebook = new global::Gtk.Notebook();
		this.MainNotebook.WidthRequest = 740;
		this.MainNotebook.HeightRequest = 500;
		this.MainNotebook.CanFocus = true;
		this.MainNotebook.Name = "MainNotebook";
		this.MainNotebook.CurrentPage = 0;
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.LayoutPageData = new global::Gtk.Fixed();
		this.LayoutPageData.Name = "LayoutPageData";
		this.LayoutPageData.HasWindow = false;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.LabelTrainingData = new global::Gtk.Label();
		this.LabelTrainingData.Name = "LabelTrainingData";
		this.LabelTrainingData.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Training Data</b>");
		this.LabelTrainingData.UseMarkup = true;
		this.LayoutPageData.Add(this.LabelTrainingData);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.LabelTrainingData]));
		w2.X = 30;
		w2.Y = 20;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.FilenameTrainingData = new global::Gtk.Entry();
		this.FilenameTrainingData.WidthRequest = 400;
		this.FilenameTrainingData.Name = "FilenameTrainingData";
		this.FilenameTrainingData.IsEditable = true;
		this.FilenameTrainingData.InvisibleChar = '•';
		this.LayoutPageData.Add(this.FilenameTrainingData);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.FilenameTrainingData]));
		w3.X = 30;
		w3.Y = 40;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.WindowTrainingData = new global::Gtk.ScrolledWindow();
		this.WindowTrainingData.WidthRequest = 400;
		this.WindowTrainingData.HeightRequest = 140;
		this.WindowTrainingData.Name = "WindowTrainingData";
		this.WindowTrainingData.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child WindowTrainingData.Gtk.Container+ContainerChild
		this.ViewTrainingData = new global::Gtk.TextView();
		this.ViewTrainingData.WidthRequest = 0;
		this.ViewTrainingData.HeightRequest = 0;
		this.ViewTrainingData.Name = "ViewTrainingData";
		this.ViewTrainingData.Editable = false;
		this.ViewTrainingData.CursorVisible = false;
		this.ViewTrainingData.AcceptsTab = false;
		this.WindowTrainingData.Add(this.ViewTrainingData);
		this.LayoutPageData.Add(this.WindowTrainingData);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.WindowTrainingData]));
		w5.X = 30;
		w5.Y = 70;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.LabelTestData = new global::Gtk.Label();
		this.LabelTestData.Name = "LabelTestData";
		this.LabelTestData.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Test Data</b>");
		this.LabelTestData.UseMarkup = true;
		this.LayoutPageData.Add(this.LabelTestData);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.LabelTestData]));
		w6.X = 30;
		w6.Y = 220;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.FilenameTestData = new global::Gtk.Entry();
		this.FilenameTestData.WidthRequest = 400;
		this.FilenameTestData.Name = "FilenameTestData";
		this.FilenameTestData.IsEditable = true;
		this.FilenameTestData.InvisibleChar = '•';
		this.LayoutPageData.Add(this.FilenameTestData);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.FilenameTestData]));
		w7.X = 30;
		w7.Y = 240;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.WindowTestData = new global::Gtk.ScrolledWindow();
		this.WindowTestData.WidthRequest = 400;
		this.WindowTestData.HeightRequest = 140;
		this.WindowTestData.Name = "WindowTestData";
		this.WindowTestData.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child WindowTestData.Gtk.Container+ContainerChild
		this.ViewTestData = new global::Gtk.TextView();
		this.ViewTestData.CanFocus = true;
		this.ViewTestData.Name = "ViewTestData";
		this.ViewTestData.AcceptsTab = false;
		this.WindowTestData.Add(this.ViewTestData);
		this.LayoutPageData.Add(this.WindowTestData);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.WindowTestData]));
		w9.X = 30;
		w9.Y = 270;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.OpenTrainingDataButton = new global::Gtk.Button();
		this.OpenTrainingDataButton.CanFocus = true;
		this.OpenTrainingDataButton.Name = "OpenTrainingDataButton";
		this.OpenTrainingDataButton.FocusOnClick = false;
		global::Gtk.Image w10 = new global::Gtk.Image();
		w10.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
		this.OpenTrainingDataButton.Image = w10;
		this.LayoutPageData.Add(this.OpenTrainingDataButton);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.OpenTrainingDataButton]));
		w11.X = 440;
		w11.Y = 40;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.ReloadTrainingDataButton = new global::Gtk.Button();
		this.ReloadTrainingDataButton.CanFocus = true;
		this.ReloadTrainingDataButton.Name = "ReloadTrainingDataButton";
		this.ReloadTrainingDataButton.FocusOnClick = false;
		global::Gtk.Image w12 = new global::Gtk.Image();
		w12.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-refresh", global::Gtk.IconSize.Menu);
		this.ReloadTrainingDataButton.Image = w12;
		this.LayoutPageData.Add(this.ReloadTrainingDataButton);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.ReloadTrainingDataButton]));
		w13.X = 470;
		w13.Y = 40;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.OpenTestDataButton = new global::Gtk.Button();
		this.OpenTestDataButton.CanFocus = true;
		this.OpenTestDataButton.Name = "OpenTestDataButton";
		this.OpenTestDataButton.FocusOnClick = false;
		global::Gtk.Image w14 = new global::Gtk.Image();
		w14.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
		this.OpenTestDataButton.Image = w14;
		this.LayoutPageData.Add(this.OpenTestDataButton);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.OpenTestDataButton]));
		w15.X = 440;
		w15.Y = 240;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.ReloadTestDataButton = new global::Gtk.Button();
		this.ReloadTestDataButton.Name = "ReloadTestDataButton";
		this.ReloadTestDataButton.FocusOnClick = false;
		global::Gtk.Image w16 = new global::Gtk.Image();
		w16.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-refresh", global::Gtk.IconSize.Menu);
		this.ReloadTestDataButton.Image = w16;
		this.LayoutPageData.Add(this.ReloadTestDataButton);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.ReloadTestDataButton]));
		w17.X = 470;
		w17.Y = 240;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.LabelDelimiters = new global::Gtk.Label();
		this.LabelDelimiters.Name = "LabelDelimiters";
		this.LabelDelimiters.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Delimiters</b>");
		this.LabelDelimiters.UseMarkup = true;
		this.LayoutPageData.Add(this.LabelDelimiters);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.LabelDelimiters]));
		w18.X = 520;
		w18.Y = 20;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.DelimiterBox = global::Gtk.ComboBox.NewText();
		this.DelimiterBox.WidthRequest = 150;
		this.DelimiterBox.Name = "DelimiterBox";
		this.LayoutPageData.Add(this.DelimiterBox);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.DelimiterBox]));
		w19.X = 520;
		w19.Y = 40;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.LabelInputNodes = new global::Gtk.Label();
		this.LabelInputNodes.Name = "LabelInputNodes";
		this.LabelInputNodes.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Input Layer Nodes</b>");
		this.LabelInputNodes.UseMarkup = true;
		this.LayoutPageData.Add(this.LabelInputNodes);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.LabelInputNodes]));
		w20.X = 520;
		w20.Y = 80;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.InputLayerNodes = new global::Gtk.SpinButton(1D, 10000D, 1D);
		this.InputLayerNodes.WidthRequest = 150;
		this.InputLayerNodes.Name = "InputLayerNodes";
		this.InputLayerNodes.Adjustment.PageIncrement = 1D;
		this.InputLayerNodes.ClimbRate = 1D;
		this.InputLayerNodes.Numeric = true;
		this.InputLayerNodes.Value = 1D;
		this.LayoutPageData.Add(this.InputLayerNodes);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.InputLayerNodes]));
		w21.X = 520;
		w21.Y = 100;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.LabelCategories = new global::Gtk.Label();
		this.LabelCategories.Name = "LabelCategories";
		this.LabelCategories.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Classification Categories</b>");
		this.LabelCategories.UseMarkup = true;
		this.LayoutPageData.Add(this.LabelCategories);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.LabelCategories]));
		w22.X = 520;
		w22.Y = 140;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.Categories = new global::Gtk.SpinButton(1D, 10000D, 1D);
		this.Categories.WidthRequest = 150;
		this.Categories.Name = "Categories";
		this.Categories.Adjustment.PageIncrement = 1D;
		this.Categories.ClimbRate = 1D;
		this.Categories.Numeric = true;
		this.Categories.Value = 1D;
		this.LayoutPageData.Add(this.Categories);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.Categories]));
		w23.X = 520;
		w23.Y = 160;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Training Examples</b>");
		this.label11.UseMarkup = true;
		this.LayoutPageData.Add(this.label11);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.label11]));
		w24.X = 520;
		w24.Y = 200;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.Examples = new global::Gtk.SpinButton(0D, 100000D, 1D);
		this.Examples.WidthRequest = 150;
		this.Examples.Name = "Examples";
		this.Examples.Adjustment.PageIncrement = 1D;
		this.Examples.ClimbRate = 1D;
		this.Examples.Numeric = true;
		this.LayoutPageData.Add(this.Examples);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.Examples]));
		w25.X = 520;
		w25.Y = 220;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.LabelSamples = new global::Gtk.Label();
		this.LabelSamples.Name = "LabelSamples";
		this.LabelSamples.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Test samples</b>");
		this.LabelSamples.UseMarkup = true;
		this.LayoutPageData.Add(this.LabelSamples);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.LabelSamples]));
		w26.X = 520;
		w26.Y = 260;
		// Container child LayoutPageData.Gtk.Fixed+FixedChild
		this.Samples = new global::Gtk.SpinButton(0D, 100000D, 1D);
		this.Samples.WidthRequest = 150;
		this.Samples.Name = "Samples";
		this.Samples.Adjustment.PageIncrement = 1D;
		this.Samples.ClimbRate = 1D;
		this.Samples.Numeric = true;
		this.LayoutPageData.Add(this.Samples);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageData[this.Samples]));
		w27.X = 520;
		w27.Y = 280;
		this.MainNotebook.Add(this.LayoutPageData);
		// Notebook tab
		this.LabelPageData = new global::Gtk.Label();
		this.LabelPageData.Name = "LabelPageData";
		this.LabelPageData.LabelProp = global::Mono.Unix.Catalog.GetString("Data");
		this.MainNotebook.SetTabLabel(this.LayoutPageData, this.LabelPageData);
		this.LabelPageData.ShowAll();
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.LayoutPageTraining = new global::Gtk.Fixed();
		this.LayoutPageTraining.Name = "LayoutPageTraining";
		this.LayoutPageTraining.HasWindow = false;
		this.MainNotebook.Add(this.LayoutPageTraining);
		global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook[this.LayoutPageTraining]));
		w29.Position = 1;
		// Notebook tab
		this.LabelPageTraining = new global::Gtk.Label();
		this.LabelPageTraining.Name = "LabelPageTraining";
		this.LabelPageTraining.LabelProp = global::Mono.Unix.Catalog.GetString("Training");
		this.MainNotebook.SetTabLabel(this.LayoutPageTraining, this.LabelPageTraining);
		this.LabelPageTraining.ShowAll();
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.LayoutPageNetwork = new global::Gtk.Fixed();
		this.LayoutPageNetwork.Name = "LayoutPageNetwork";
		this.LayoutPageNetwork.HasWindow = false;
		this.MainNotebook.Add(this.LayoutPageNetwork);
		global::Gtk.Notebook.NotebookChild w30 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook[this.LayoutPageNetwork]));
		w30.Position = 2;
		// Notebook tab
		this.LabelPageNetwork = new global::Gtk.Label();
		this.LabelPageNetwork.Name = "LabelPageNetwork";
		this.LabelPageNetwork.LabelProp = global::Mono.Unix.Catalog.GetString("Network");
		this.MainNotebook.SetTabLabel(this.LayoutPageNetwork, this.LabelPageNetwork);
		this.LabelPageNetwork.ShowAll();
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.LayoutPagePlot = new global::Gtk.Fixed();
		this.LayoutPagePlot.Name = "LayoutPagePlot";
		this.LayoutPagePlot.HasWindow = false;
		this.MainNotebook.Add(this.LayoutPagePlot);
		global::Gtk.Notebook.NotebookChild w31 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook[this.LayoutPagePlot]));
		w31.Position = 3;
		// Notebook tab
		this.LabelPagePlot = new global::Gtk.Label();
		this.LabelPagePlot.Name = "LabelPagePlot";
		this.LabelPagePlot.LabelProp = global::Mono.Unix.Catalog.GetString("Plot");
		this.MainNotebook.SetTabLabel(this.LayoutPagePlot, this.LabelPagePlot);
		this.LabelPagePlot.ShowAll();
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.LayoutPageAbout = new global::Gtk.Fixed();
		this.LayoutPageAbout.Name = "LayoutPageAbout";
		this.LayoutPageAbout.HasWindow = false;
		this.MainNotebook.Add(this.LayoutPageAbout);
		global::Gtk.Notebook.NotebookChild w32 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook[this.LayoutPageAbout]));
		w32.Position = 4;
		// Notebook tab
		this.LabelPageAbout = new global::Gtk.Label();
		this.LabelPageAbout.Name = "LabelPageAbout";
		this.LabelPageAbout.LabelProp = global::Mono.Unix.Catalog.GetString("About");
		this.MainNotebook.SetTabLabel(this.LayoutPageAbout, this.LabelPageAbout);
		this.LabelPageAbout.ShowAll();
		this.MainLayout.Add(this.MainNotebook);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.MainNotebook]));
		w33.X = 30;
		w33.Y = 70;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'MainToolbar\'><toolitem name=\'AboutButton\' action=\'AboutButton\'" +
				"/><toolitem name=\'QuitButton\' action=\'QuitButton\'/></toolbar></ui>");
		this.MainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/MainToolbar")));
		this.MainToolbar.Name = "MainToolbar";
		this.MainToolbar.ShowArrow = false;
		this.MainToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.MainLayout.Add(this.MainToolbar);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.MainToolbar]));
		w34.X = 30;
		w34.Y = 20;
		this.Add(this.MainLayout);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.AboutButton.Activated += new global::System.EventHandler(this.OnAboutButtonClicked);
		this.QuitButton.Activated += new global::System.EventHandler(this.OnQuitButtonClicked);
		this.MainNotebook.SwitchPage += new global::Gtk.SwitchPageHandler(this.OnMainNotebookSwitchPage);
		this.OpenTrainingDataButton.Clicked += new global::System.EventHandler(this.OnOpenTrainingDataButtonClicked);
		this.ReloadTrainingDataButton.Clicked += new global::System.EventHandler(this.OnReloadTrainingDataButtonClicked);
		this.OpenTestDataButton.Clicked += new global::System.EventHandler(this.OnOpenTestDataButtonClicked);
		this.ReloadTestDataButton.Clicked += new global::System.EventHandler(this.OnReloadTestDataButtonClicked);
	}
}
